const styles = StyleSheet.create({
  colouredRectangle: {
    // display: "flex",
    // justifyContent: "flex-start",
    // flexDirection: "column",
    height: "100%",
    // width: "100%",
    backgroundColor: colourSwitch(pokeTypeList?[0]),
  },
  statsRectangle: {
    // display: "flex",
    // // justifyContent: "flex-end",
    // flexDirection: "column",
    // flexGrow: 4,
    position: "absolute",
    top: 250,
    height: 600,
    width: "100%",
    backgroundColor: "#FFFEFD",
    borderRadius: 60,
  },
  pokemonNameContainer: {
    padding: 15,
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
  },
  pokemonName: {
    color: "white",
    fontSize: 50,
  },
  pokemonSprite: {
    position: "absolute",
    top: 70,
    left: 70,
  },
  infoBars: {
    position: "relative",
    top: "10%",
    left: "7%",
    backgroundColor: "#C5E7F5",
    width: 341,
    height: 42,
    padding: 10,
    marginVertical: 8,
    marginHorizontal: 16,
    borderRadius: 35,
  },
  pokeTypeIndivid: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "nowrap",
    top: "5%",
    left: "7%",
    padding: 10,
    marginHorizontal: 10,
    height: 42,
    width: "20%",
    backgroundColor: "#3692DC",
    borderRadius: 35,
  },
  typesContainer: {
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    flexWrap: "nowrap",
    // marginVertical: 50,
    paddingTop: 150,
  },
});